version: '3.8'
services:
  trader:
    build: .
    depends_on:
      - ocr
      - db
    env_file: .env
    volumes:
      - logs:/app/logs
    restart: unless-stopped

  ocr:
    image: tesseractshadow/tesseract4re:latest
    volumes:
      - ./screenshots:/data
    restart: on-failure

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: trading_logs
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  logs:
  dbdata: